Vagrant.configure("2") do |config|
  config.vm.box = "hallsholicker/centos8-stream-k8s"

  config.vm.define "k8s-controller-1" do |controller1|
    controller1.vm.network "private_network", ip: "192.168.56.11"
    controller1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/kubernetes-onprem-labs"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.name = "k8s-controller-1"
      v.memory = 2048
      v.cpus = 2
      v.linked_clone = true
    end
    controller1.vm.provision "shell", inline: <<-SHELL
      sudo -i
      sudo echo "192.168.57.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo echo "192.168.58.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo ip route add 192.168.57.0/24 via 192.168.56.100
      sudo ip route add 192.168.58.0/24 via 192.168.56.100
    
    SHELL
  end

  config.vm.define "k8s-controller-2" do |controller2|
    controller2.vm.network "private_network", ip: "192.168.56.12"
    controller2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/kubernetes-onprem-labs"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.name = "k8s-controller-2"
      v.memory = 2048
      v.cpus = 2
      v.linked_clone = true
    end
    controller2.vm.provision "shell", inline: <<-SHELL
      sudo -i
      sudo echo "192.168.57.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo echo "192.168.58.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo ip route add 192.168.57.0/24 via 192.168.56.100
      sudo ip route add 192.168.58.0/24 via 192.168.56.100
    
    SHELL
  end

  config.vm.define "k8s-controller-3" do |controller3|
    controller3.vm.network "private_network", ip: "192.168.56.13"
    controller3.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/kubernetes-onprem-labs"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.name = "k8s-controller-3"
      v.memory = 2048
      v.cpus = 2
      v.linked_clone = true
    end
    controller3.vm.provision "shell", inline: <<-SHELL
      sudo -i
      sudo echo "192.168.57.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo echo "192.168.58.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo ip route add 192.168.57.0/24 via 192.168.56.100
      sudo ip route add 192.168.58.0/24 via 192.168.56.100
      
    SHELL
  end

  config.vm.define "k8s-worker-1" do |worker1|
    worker1.vm.network "private_network", ip: "192.168.56.21"
    worker1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/kubernetes-onprem-labs"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.name = "k8s-worker-1"
      v.memory = 1536
      v.cpus = 2
      v.linked_clone = true
    end
    worker1.vm.provision "shell", inline: <<-SHELL
      sudo -i
      sudo echo "192.168.57.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo echo "192.168.58.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo ip route add 192.168.57.0/24 via 192.168.56.100
      sudo ip route add 192.168.58.0/24 via 192.168.56.100
    
    SHELL
  end

  config.vm.define "k8s-worker-2" do |worker2|
    worker2.vm.network "private_network", ip: "192.168.56.22"
    worker2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/kubernetes-onprem-labs"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.name = "k8s-worker-2"
      v.memory = 1536
      v.cpus = 2
      v.linked_clone = true
    end
    worker2.vm.provision "shell", inline: <<-SHELL
      sudo -i
      sudo echo "192.168.57.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo echo "192.168.58.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo ip route add 192.168.57.0/24 via 192.168.56.100
      sudo ip route add 192.168.58.0/24 via 192.168.56.100
    
    SHELL
  end

  config.vm.define "k8s-worker-3" do |worker3|
    worker3.vm.network "private_network", ip: "192.168.57.23"
    worker3.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/kubernetes-onprem-labs"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.name = "k8s-worker-3"
      v.memory = 1536
      v.cpus = 2
      v.linked_clone = true
    end
    worker3.vm.provision "shell", inline: <<-SHELL
      sudo -i
      sudo echo "192.168.56.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo echo "192.168.58.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo ip route add 192.168.56.0/24 via 192.168.57.100
      sudo ip route add 192.168.58.0/24 via 192.168.57.100
    
    SHELL
  end
  
  config.vm.define "k8s-router" do |router|
    router.vm.network "private_network", ip: "192.168.56.100"
    router.vm.network "private_network", ip: "192.168.57.100"
    router.vm.network "private_network", ip: "192.168.58.100"
    router.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/kubernetes-onprem-labs"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.name = "k8s-router"
      v.memory = 1024
      v.cpus = 1
      v.linked_clone = true
    end
    router.vm.provision "shell", inline: <<-SHELL
      sudo -i
      sudo echo "net.ipv4.ip_forward=1" > /etc/sysctl.conf
      sudo sysctl -p

      SHELL
  end

  config.vm.define "k8s-client" do |client|
    client.vm.network "private_network", ip: "192.168.58.10"
    client.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/kubernetes-onprem-labs"]
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.name = "k8s-client"
      v.memory = 1024
      v.cpus = 1
      v.linked_clone = true
    end
    client.vm.provision "shell", inline: <<-SHELL
      sudo -i
      sudo echo "192.168.56.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo echo "192.168.57.0/24 via 192.168.56.100" >> /etc/sysconfig/network-scripts/route-enp0s8
      sudo ip route add 192.168.56.0/24 via 192.168.58.100
      sudo ip route add 192.168.57.0/24 via 192.168.58.100
    SHELL
  end
end

