- name: Set hostname
  command: "hostnamectl set-hostname {{ hostname }}"
  become: true

- name: Add /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items:
    - { ip: "192.168.56.10", hostname: "k8s-controller" }
    - { ip: "192.168.56.11", hostname: "k8s-controller-1" }
    - { ip: "192.168.56.12", hostname: "k8s-controller-2" }
    - { ip: "192.168.56.13", hostname: "k8s-controller-3" }
    - { ip: "192.168.56.21", hostname: "k8s-worker-1" }
    - { ip: "192.168.56.22", hostname: "k8s-worker-2" }
    - { ip: "192.168.57.23", hostname: "k8s-worker-3" }
    - { ip: "192.168.56.100", hostname: "k8s-router" }
    - { ip: "192.168.58.10", hostname: "k8s-client" }
  become: true
  when:
    - "'Client' not in group_names"
